#!/bin/bash

#=======================================================================
# Add_test
# File ID: 948f70c2-f989-11dd-be4a-000475e441b9
#
# Create new *.t file in the current directory. Specify a name without 
# the .t extension and a file with some common option tests will be 
# created.
#
# License: GNU General Public License version 2 or later.
#=======================================================================

[ -z "$1" ] && { echo Syntax: $0 testname >&2; exit 1; }

name=$1
std -l perl-tests $name.t -t progname=$name -t exec=../$name -t testcmd=$name.t
chmod +x $name.t
