#=======================================================================
# t/Makefile
# File ID: cb308c44-279d-11e5-ab18-000df06acc56
#=======================================================================

.PHONY: all
all: test

.PHONY: clean
clean:

.PHONY: test
test:
	./gitspreadd.t
